-- Data Definitation Language

CREATE DATABASE PetClinics

USE PetClinics

CREATE TABLE Clinica(
IdClinica INT PRIMARY KEY IDENTITY,
RazaoSocial VARCHAR(255) NOT NULL,
Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE Dono(
IdDono INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL
);

CREATE TABLE TipoPet(
IdTipoPet INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(255) NOT NULL
);

CREATE TABLE Veterinario(
IdVet INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
CRMV VARCHAR(10) NOT NULL,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
);

CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(255) NOT NULL,
IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)
);

CREATE TABLE Pet(
IdPet INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
Telefone VARCHAR(15) NOT NULL, 
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca)
);

CREATE TABLE Atendimento(
IdAtendimento INT PRIMARY KEY IDENTITY,
DataAtendimento Date NOT NULL,
Descricao VARCHAR(255),
IdVet INT FOREIGN KEY REFERENCES Veterinario(IdVet),
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet)
);

