CREATE DATABASE ECommerce;

USE ECommerce;

CREATE TABLE Lojas(
IdLoja INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL
);

GO

CREATE TABLE Clientes(
IdCliente INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL
);

GO

CREATE TABLE Categorias(
IdCategoria INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
IdLoja INT FOREIGN KEY REFERENCES Lojas(IdLoja)
);

GO

CREATE TABLE Subcategorias(
IdSubcategoria INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria)
);

GO

CREATE TABLE Produtos(
IdProduto INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
Valor DECIMAL NOT NULL,
IdSubcategoria INT FOREIGN KEY REFERENCES SubCategorias(IdSubcategoria)
);

GO

CREATE TABLE Pedidos(
IdPedido INT PRIMARY KEY IDENTITY,
NrPedido VARCHAR(255) NOT NULL,
DataPedido DATE,
StatusP VARCHAR(255) NOT NULL,
IdCliente INT FOREIGN KEY REFERENCES Clientes(IdCliente)
);

GO

CREATE TABLE PedidosProdutos(
IdPedido INT NOT NULL,
IdProduto INT NOT NULL);

GO