CREATE DATABASE Gufi;
GO

USE Gufi;
GO


CREATE TABLE TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TituloUsuario VARCHAR(255) NOT NULL
);
GO

CREATE TABLE TipoEvento(
	IdTipoEvento INT PRIMARY KEY IDENTITY,
	TituloEvento VARCHAR(255) NOT NULL UNIQUE 
);

GO


CREATE TABLE Instituicao(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	NomeFantasia VARCHAR(255) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL UNIQUE
);



CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	DataCadastro VARCHAR(255) NOT NULL,
	Genero VARCHAR(255) NOT NULL
);
- - - 


CREATE TABLE Evento(
	IdEvento INT PRIMARY KEY IDENTITY,
	NomeEvento VARCHAR(255) NOT NULL,
	AcessoLivre VARCHAR(255) NOT NULL,
	DataEvento VARCHAR(255) NOT NULL,
	Descricao VARCHAR(255) NOT NULL
);


CREATE TABLE Presenca(
	IdPresenca INT PRIMARY KEY IDENTITY,
	Situacao VARCHAR(255) NOT NULL
);