-- DDL
CREATE DATABASE LocadoraM;

USE LocadoraM;

CREATE TABLE Empresa(
IdEmpresa INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Cliente(
IdCliente INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
CPF VARCHAR(16) NOT NULL
);

CREATE TABLE Marca(
IdMarca INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Modelo(
IdModelo INT PRIMARY KEY IDENTITY,
Nome VARCHAR(255) NOT NULL,
IdMarca INT FOREIGN KEY REFERENCES  Marca(IdMarca) 
);

CREATE TABLE Veiculo(
IdVeiculo INT PRIMARY KEY IDENTITY,
Placa VARCHAR(10) NOT NULL,
IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo)
);

CREATE TABLE Aluguel(
IdAluguel INT PRIMARY KEY IDENTITY,
DataInicio DATE NOT NULL,
DataFim DATE,
IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo)
);